//includes generated by Qt Creator
#include "glavnookno.h"
#include "ui_glavnookno.h"
#include "zacetnookno.h"
#include <QtMultimedia/QMediaPlaylist>
#include <QtMultimedia/QMediaPlayer>

glavnookno::glavnookno(QWidget *parent) :
  QMainWindow(parent),
  ui(new Ui::glavnookno)
{
  timer=new QTimer(this);
  ui->setupUi(this);
  connect(ui->actionZacni_igro, SIGNAL(triggered()), this, SLOT(start()));
  connect(ui->actionUndo, SIGNAL(triggered()), this, SLOT(undo2()));
  connect(ui->volume, SIGNAL(clicked()), this, SLOT(setMusic()));
  this->igra = NULL;
  this->igra2=NULL;
  this->igra3=NULL;
  this->i1 = NULL;
  this->i2 = NULL;
  ch = new ClickHandler(this);
  igP = ui->igralnaP;
  volume = ui->volume;
  for(int i = 0; i<6; i++)
    for(int j = 0; j<7; j++){
      QWidget* w = (QWidget*)ui->igralnaP->itemAtPosition(i, j+1)->widget();
      w->installEventFilter(ch);
    }
  statusLabel = new QLabel(this);
  statusLabel->setLayoutDirection(Qt::LeftToRight);
  ui->statusBar->addPermanentWidget(statusLabel);
  //timer:
  timer = new QTimer(this);
  connect(timer,SIGNAL(timeout()), this, SLOT(izpiscas()));
  z = NULL;
}

glavnookno::~glavnookno()
{
  //počisti pomnilnik ko zaključiš program
  if(igra != NULL){
    delete igra;
    igra = NULL;
  }
  if(igra2!=NULL){
      delete igra2;
      igra2 = NULL;
  }
  if(igra3!=NULL){
      delete igra3;
      igra3 = NULL;
  }
  if(i1 != NULL && i2 != NULL){
    delete i1;
    i1 = NULL;
    delete i2;
    i2 = NULL;
  }
  if(igP != NULL)
    igP = NULL;
  z = NULL;
  delete ui;
}

void glavnookno::start(){
  //ovde se pokliče funkcija za začetek nove igre
   // printf("%d\n",ttip);

    if(ttip==1){
        if(i1 == NULL && i2 == NULL)
          vnosImen();
        if(igra != NULL){
          delete igra;
          igra = NULL;
        }
        igra = new Igra(i1, i2);
        if(z != NULL)
          igra->setNaVrsti(z);
        cas = new QTime(0,0,0);
        timer->start(1000);
        if(igra->locked())
          igra->lock();
        this->updateUi();
        this->clearPolje();
    }else if(ttip==2){
        if(i1 == NULL && i2 == NULL)
          vnosImen();
        if(igra2 != NULL){
          delete igra2;
          igra2 = NULL;
        }
        igra2 = new Igra2(i1, i2);
        if(z != NULL)
          igra2->setNaVrsti(z);
        cas = new QTime(0,0,0);
        timer->start(1000);
        if(igra2->locked()){
            igra2->lock();
        }
          //igra2->lock();
        this->updateUi();
        this->clearPolje();
    }else if(ttip==3){
        if(i1 == NULL && i2 == NULL)
          vnosImen();
        if(igra3 != NULL){
          delete igra3;
          igra3 = NULL;
        }
        igra3 = new Igra3(i1, i2);
        if(z != NULL)
          igra3->setNaVrsti(z);
        cas = new QTime(0,0,0);
        timer->start(1000);
        if(igra3->locked())
          igra3->lock();
        this->updateUi();
        this->clearPolje();
    }
}

void glavnookno::izpiscas(){
  *cas = cas->addSecs(1);//tick
  ui->cas->setText(cas->toString("hh:mm:ss"));
}

//funkcija za vnos imen
void glavnookno::vnosImen(){
  QString imeI, imeII;
  QDialog *dI = new QDialog(0,0),
      *dII = new QDialog(0,0);
  Ui_vnosImena1 vi1;
  Ui_vnosImena2 vi2;
  vi1.setupUi(dI);
  dI->exec();
  imeI = vi1.txtIme->text();
  i1 = new Igralec(imeI, 1);
  vi2.setupUi(dII);
  dII->exec();
  imeII = vi2.txtIme->text();
  i2 = new Igralec(imeII, 2);
}

void glavnookno::setPolje(int x, int y, int i){
  QWidget *w = (QWidget*)ui->igralnaP->itemAtPosition(x, y+1)->widget();
  if(i == 1)
    w->setStyleSheet("border-image: url(:/img/tileR.png);");
  else if(i == 2)
    w->setStyleSheet("border-image: url(:/img/tileY.png);");
  else if(i==0){
    w->setStyleSheet("border-image: url(:/img/tile.png);\nbackground-color: rgba(255, 255, 255, 200);");
    if(ttip==1){
        igra->polje[x][y]=0;
    }else if(ttip==2){
        igra2->polje[x][y]=0;
    }else if(ttip==3){
        igra3->polje[x][y]=0;
    }

  }
  this->updateUi();
}

void glavnookno::undo2(){
  int* u;// = this->igra->undo2();
  if(ttip==1){
      u=this->igra->undo2();
  }else if(ttip==2){
      u=this->igra2->undo2();
  }else if(ttip==3){
      u=this->igra3->undo2();
  }
  if(u[0] == 0)
    this->setPolje(u[1], u[2], u[0]);
  else
    QMessageBox::warning(this, "Napaka", "Ni možno izvesti undo", QMessageBox::Ok, QMessageBox::Cancel);
}

void glavnookno::setMusic(){
    QPushButton *p = (QPushButton*)ui->volume;
    QMediaPlayer *m = new QMediaPlayer();
    if(p->styleSheet()=="border-image: url(:/img/SoundON.png);")
    {
        p->setStyleSheet("border-image: url(:/img/SoundOFF.png);");
        m->pause();
    }
    else if(p->styleSheet()=="border-image: url(:/img/SoundOFF.png);")
    {
        p->setStyleSheet("border-image: url(:/img/SoundON.png);");
        m->play();
    }
    this->updateUi();
}

void glavnookno::clearPolje(){
  for(int i = 0; i<6; i++)
    for(int j = 0; j<7; j++){
      QWidget* w = (QWidget*)ui->igralnaP->itemAtPosition(i, j+1)->widget();
      w->setStyleSheet("border-image: url(:/img/tile.png);\nbackground-color: rgba(255, 255, 255, 200);");
    }
}

void glavnookno::ilegalMove(){
  QMessageBox::warning(this, "Napaka", "Nedovoljena poteza", QMessageBox::Ok, QMessageBox::Cancel);
}

void glavnookno::updateUi(){
  ui->txtIgralec1->setText(i1->getIme());
  ui->txtIgralec2->setText(i2->getIme());
  ui->lblScore1->setText(QString::number(i1->getZmage()));
  ui->lblScore2->setText(QString::number(i2->getZmage()));
  if(ttip==1){
      statusLabel->setText("Na vrsti je: " + igra->getNaVrsti()->getIme());
  }else if(ttip==2){
      statusLabel->setText("Na vrsti je: " + igra2->getNaVrsti()->getIme());
  }else if(ttip==3){
      statusLabel->setText("Na vrsti je: " + igra3->getNaVrsti()->getIme());
  }
  //statusLabel->setText("Na vrsti je: " + igra->getNaVrsti()->getIme());
}

void glavnookno::zmagovalec(int z){
  QDialog* d = new QDialog(0,0);
  if(ttip==1){
      igra->lock();
  }else if(ttip==3){
      igra3->lock();
  }
  //igra->lock();
  if(z==0){
    Ui_izpis_neodloceno nUi;
    nUi.setupUi(d);
    int s = d->exec();
    if (s == QDialog::Accepted)
      this->start();
    else
      timer->stop();
  } else {
    updateUi();
    Ui_Izpis_zmagovalca zUi;
    zUi.setupUi(d);
    if(i1->getSt() == z){
        i1->zmaga();
        this->z = i1;
        zUi.lblWin->setText(zUi.lblWin->text() + " " + i1->getIme());
    } else {
        i2->zmaga();
        this->z = i2;
        zUi.lblWin->setText(zUi.lblWin->text() + " " + i2->getIme());
    }
    int s = d->exec();

    if (s == QDialog::Accepted)
      this->start();
    else {
      timer->stop();
      updateUi();
    }
  }
}

void glavnookno::zmagovalec2(int z){
    QDialog* d = new QDialog(0,0);
    //igra2->lock();
    /*
    if(z==0){
        if(i1->getZmage()>i2->getZmage()){
            i1->zmaga();
            this->z = i1;
            zUi.lblWin->setText(zUi.lblWin->text() + " " + i1->getIme());
        }else if(i1->getZmage()<i2->getZmage()){
            i2->zmaga();
            this->z = i2;
            zUi.lblWin->setText(zUi.lblWin->text() + " " + i2->getIme());
        }else{
            Ui_izpis_neodloceno nUi;
            nUi.setupUi(d);
            int s = d->exec();
            if (s == QDialog::Accepted)
              this->start();
            else
              timer->stop();
        }
    }*/
    if(i1->getSt() == z){
        i1->zmaga();
        this->z = i1;
    } else if(i2->getSt()==z){
        i2->zmaga();
        this->z = i2;
    }else if(z==0){
        if(i1->getZmage()>i2->getZmage()){
            Ui_Izpis_zmagovalca zUi;
            zUi.setupUi(d);
            zUi.lblWin->setText(zUi.lblWin->text() + " " + i1->getIme());
            int s = d->exec();

            if (s == QDialog::Accepted)
              this->start();
            else {
              timer->stop();
             }
              //updateUi();
        }else if(i2->getZmage()>i1->getZmage()){
            Ui_Izpis_zmagovalca zUi;
            zUi.setupUi(d);
            zUi.lblWin->setText(zUi.lblWin->text() + " " + i2->getIme());
            int s = d->exec();

            if (s == QDialog::Accepted)
              this->start();
            else {
              timer->stop();
            }
              //updateUi();
        }else if(i1->getZmage()==i2->getZmage()){
            Ui_izpis_neodloceno nUi;
            nUi.setupUi(d);
            int s = d->exec();
            if (s == QDialog::Accepted)
              this->start();
            else
              timer->stop();
        }
    }
    updateUi();
}

void glavnookno::on_undo_clicked()
{
 //naslov
 /*  int* ii=igra->undo();
     printf("%p\n",ii);
     setPolje();*/
     //printf("velikost  %d\n",igra->velikost());
    if(ttip==1){
        if(igra->velikost()>0){
            int ii=igra->undo();
            int jj=igra->undo();
            //printf("%d %d\n",ii,jj);
            setPolje(ii,jj,0);
            igra->getNaVrsti()->getSt();
         }
    }else if(ttip==2){
        if(igra2->velikost()>0){
            int ii=igra2->undo();
            int jj=igra2->undo();
            //printf("%d %d\n",ii,jj);
            setPolje(ii,jj,0);
            igra2->getNaVrsti()->getSt();
         }
    }else if(ttip==3){
        if(igra3->velikost()>0){
            int ii=igra3->undo();
            int jj=igra3->undo();
            //printf("%d %d\n",ii,jj);
            setPolje(ii,jj,0);
            igra3->getNaVrsti()->getSt();
         }
    }/*
     if(igra->velikost()>0){
         int ii=igra->undo();
         int jj=igra->undo();
         //printf("%d %d\n",ii,jj);
         setPolje(ii,jj,0);
         igra->getNaVrsti()->getSt();
      }*/
}
